apiVersion: v1
kind: Pod
metadata:
  name: django-pod
spec:
  containers:
    - name: django-app
      image: trainwithshubham/django-todo:latest
      ports:
        - containerPort: 8000
~                                                                                                                                               
~                                                                                                                                               
~                                                                                                                                               
~                                                                                                                                               
~                                                                                                                                               
~                                
